name: smekho_viktorina
description: Смешная викторина
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.3.2
  yandex_mobileads: ^7.17.0
  audioplayers: ^5.2.1
  url_launcher: ^6.3.0
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/questions.json
    - assets/images/
    - assets/sounds/
    - assets/icon.png